<Project ToolsVersion="15.0" xmlns="http://schemas.microsoft.com/developer/msbuild/2003">

  <PropertyGroup>
    <Configuration Condition=" '$(Configuration)' == '' ">Release</Configuration>
    <Platform Condition=" '$(Platform)' == '' ">AnyCPU</Platform>

    <OutputPath>bin\$(Configuration)\</OutputPath>
    <TargetFrameworkVersion>v4.7.2</TargetFrameworkVersion>
    <AssemblyName>KRASH_VisualsBridge</AssemblyName>
    <RootNamespace>KRASH_VisualsBridge</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <Reference Include="Assembly-CSharp">
      <HintPath>lib\Assembly-CSharp.dll</HintPath>
    </Reference>

    <Reference Include="UnityEngine">
      <HintPath>lib\UnityEngine.dll</HintPath>
    </Reference>
  </ItemGroup>

  <ItemGroup>
    <Compile Include="Source\KRASH_VisualsBridge.cs" />
  </ItemGroup>

</Project>